apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-monitoring-config
  namespace: {{ .Release.Namespace }}
  labels:
    extensions.gardener.cloud/configuration: monitoring
data:
  scrape_config: |
    - job_name: 'cilium-agent-metrics'
      scheme: https
      tls_config:
        # This is needed because the kubelets' certificates are not are generated
        # for a specific pod IP
{{ include "prometheus.tls-config.kube-cert-auth-insecure" . | indent 8 }}
      kubernetes_sd_configs:
      - role: endpoints
        api_server: https://kube-apiserver:443
        tls_config:
{{ include "prometheus.tls-config.kube-cert-auth" . | indent 10 }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_k8s_app]
        action: keep
        regex: cilium
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        regex: true
        action: keep
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name
      - target_label: __address__
        replacement: kube-apiserver:443
      - source_labels:
        - __meta_kubernetes_pod_name
        - __meta_kubernetes_service_annotation_prometheus_io_port
        regex: (.+);(.+)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/kube-system/pods/${1}:${2}/proxy/metrics

    - job_name: 'cilium-operator-metrics'
      scheme: https
      tls_config:
{{ include "prometheus.tls-config.kube-cert-auth-insecure" . | indent 8 }}
      kubernetes_sd_configs:
      - role: pod
        api_server: https://kube-apiserver:443
        tls_config:
{{ include "prometheus.tls-config.kube-cert-auth" . | indent 10 }}
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: \d+
        - target_label: __address__
          replacement: kube-apiserver:443
        - source_labels:
          - __meta_kubernetes_pod_name
          - __meta_kubernetes_pod_annotation_prometheus_io_port
          regex: (.+);(.+)
          target_label: __metrics_path__
          replacement: /api/v1/namespaces/kube-system/pods/${1}:${2}/proxy/metrics
  dashboard_operators: |
    cilium-dashboard.json: |-
    {{- .Files.Get "cilium-dashboard.json" | nindent 6 }}

    cilium-operator-dashboard.json: |-
    {{- .Files.Get "cilium-operator-dashboard.json" | nindent 6 }}

    hubble-dashboard.json: |-
    {{- .Files.Get "hubble-dashboard.json" | nindent 6 }}
