{
 "title": "Hubble",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "General Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flows processed Per Node",
   "type": "graph",
   "description": "Min /  Max / Avg total number of flows processed ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "min"
    },
    {
     "expr": "max(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Flows Types",
   "type": "graph",
   "description": "Total number of flows divided by type (e.g., drop / trace).",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "L7 Flow Distribution",
   "type": "graph",
   "description": "L7 flow distribution by subtype.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{type=\"L7\"}[1m])) by (pod, subtype)",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "Trace Flow Distribution",
   "type": "graph",
   "description": "Flow distribution traces by subtype (overlay, stack, or endpoint).",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{type=\"Trace\"}[1m])) by (pod, subtype)",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Forwarded vs Dropped",
   "type": "graph",
   "description": "Forwarded vs Dropped flows. ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total[1m])) by (pod, verdict)",
     "legendFormat": "{{verdict}}"
    }
   ]
  },
  {
   "title": "Drop Reason",
   "type": "graph",
   "description": "Total drops per reason for dropping. ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total[1m])) by (pod, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Protocol Usage",
   "type": "graph",
   "description": "Port distribution per protocol. ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(hubble_port_distribution_total[1m])) by (pod, protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Top 10 Port Distribution",
   "type": "graph",
   "description": "Top 10 used protocols. ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum (rate(hubble_port_distribution_total{port!=\"0\"}[1m])) by (pod, port, protocol))",
     "legendFormat": "{{port}}/{{protocol}}"
    }
   ]
  },
  {
   "title": "TCPv4",
   "type": "graph",
   "description": "TCP total messages per type (e.g., SYN, SYN-ACK, FIN,...) ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv4\"}[1m])) by (pod, flag)",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Missing TCPv4 SYN-ACKs",
   "type": "graph",
   "description": " Total number of unacknowledged SYNs. ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv4\", flag=\"SYN\"}[1m])) by (pod) - sum(rate(hubble_tcp_flags_total{family=\"IPv4\", flag=\"SYN-ACK\"}[1m])) by (pod)",
     "legendFormat": "Missing SYN-ACK"
    }
   ]
  },
  {
   "title": "ICMPv4",
   "type": "graph",
   "description": "Total number of ICMP messages per type. ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv4\"}[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Missing ICMPv4 Echo-Reply",
   "type": "graph",
   "description": "Total number of outstanding Echo requests (missing echo replies). ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv4\", type=\"EchoRequest\"}[1m])) by (pod) - sum(rate(hubble_icmp_total{family=\"IPv4\", type=\"EchoReply\"}[1m])) by (pod)",
     "legendFormat": "Missing ICMP Echo-Reply"
    }
   ]
  }
 ]
}